name: aws_setup
description: 'Sets up the environment variables and profile for jobs connecting to AWS'

inputs:
  aws-profile-name:
    description: 'The name of the AWS profile to be used later for all AWS commands'
    required: true
  aws-region:
    description: 'The AWS region to be used for all AWS commands'
    required: true
  aws-role-to-assume:
    description: 'The ARN of the AWS role to be assumed'
    required: true

runs:
  using: composite
  steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        role-session-name: ${{ inputs.aws-profile-name }}
        aws-region: ${{ inputs.aws-region }}

    - name: Setup Profile
      shell: bash
      run: |
        aws configure set region ${{ inputs.aws-region }} --profile ${{ inputs.aws-profile-name }}
        aws configure set aws_session_token ${{ env.AWS_SESSION_TOKEN }} --profile ${{ inputs.aws-profile-name }}
        aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }} --profile ${{ inputs.aws-profile-name }}
        aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }} --profile ${{ inputs.aws-profile-name }}
    
    - name: Reset AWS Environment Variables
      shell: bash
      run: |
        echo "AWS_ACCESS_KEY_ID=" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=" >> $GITHUB_ENV
        echo "AWS_SESSION_TOKEN=" >> $GITHUB_ENV
    
    # Hello from AWS: WhoAmI
    - name: Sts GetCallerIdentity
      shell: bash
      run: |
        aws sts get-caller-identity --profile ${{ inputs.aws-profile-name }}