name: build_setup
description: 'Check out code, set up python, and always configure AWS credentials for DEV stack (even if the branch is prod)'

inputs:
  branch:
    description: 'The name of the github branch that triggered the workflow'
    required: true

  dev-aws-profile-name:
    description: 'The name of the AWS profile to be used later for all AWS commands for the DEV stack'
    required: false
    default: 'Brain-DEV'
  dev-aws-region:
    description: 'The AWS region to be used for all AWS commands for the DEV stack'
    required: false
    default: 'eu-west-1'
  dev-aws-role-to-assume:
    description: 'The ARN of the AWS role to be assumed for the DEV stack'
    required: true
  
  prod-aws-profile-name:
    description: 'The name of the AWS profile to be used later for all AWS commands for the PROD stack'
    required: false
    default: 'Brain-PROD'
  prod-aws-region:
    description: 'The AWS region to be used for all AWS commands for the PROD stack'
    required: false
    default: 'eu-west-1'
  prod-aws-role-to-assume:
    description: 'The ARN of the AWS role to be assumed for the PROD stack'
    required: true # This is required for the prod stack, but will not automatically cause errors if it is not included i.e. it is not required for the dev stack

  python-version:
    description: 'The version of python to be used'
    required: false
    default: '3.12'

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Pip install from requirements.txt
      shell: bash
      run: |
        pip install -r requirements.txt

    - name: Configure git
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: configure DEV stack aws credentials
      uses: './.github/actions/aws_setup'
      with:        
        aws-profile-name: ${{ inputs.dev-aws-profile-name }}
        aws-region: ${{ inputs.dev-aws-region }}
        aws-role-to-assume: ${{ inputs.dev-aws-role-to-assume }}
    
    - name: configure PROD stack aws credentials
      if: ${{ inputs.branch == 'prod' }}
      uses: './.github/actions/aws_setup'
      with:        
        aws-profile-name: ${{ inputs.prod-aws-profile-name }}
        aws-region: ${{ inputs.prod-aws-region }}
        aws-role-to-assume: ${{ inputs.prod-aws-role-to-assume }}
