name: Lambda build and publish
description: Automatically build and publish Lambdas for DEV and PROD stacks. Deploying to actually run and be used in the stacks still requires spacelift/pulumi/aws deployment as well.

env:
    DEV_AWS_PROFILE: Brain-DEV
    DEV_AWS_REGION : "eu-west-1"
    DEV_AWS_ROLE_TO_ASSUME: arn:aws:iam::891377009928:role/GitHub_ofladby

    PROD_AWS_PROFILE: Brain-PROD
    PROD_AWS_REGION : "eu-west-1"
    PROD_AWS_ROLE_TO_ASSUME: arn:aws:iam::891377009928:role/GitHub_ofladby

on:
  push:
    branches:
      - dev
      - prod
    paths-ignore:
      - .VERSION

jobs:
  changed_files_dev:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    outputs:
      folders: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout source code
        id: checkout
        uses: actions/checkout@v4        
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          dir_names: 'true'
          dir_names_max_depth: 2
          files_ignore: |
            **.VERSION
            .gitignore
            .github/**
          dir_names_exclude_current_dir: 'true'
          matrix: 'true'

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

  Build_for_DEV_stack:
    if: ${{ github.ref_name == 'dev' }}
    needs: changed_files_dev
    strategy:
      matrix:
        folder: ${{ fromJSON( needs.changed_files_dev.outputs.folders ) }}
        max-parallel: 1
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: write    # This is required for actions/checkout and git push
    runs-on: ubuntu-latest    
    timeout-minutes: 10
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
    
      - name: Current lambda folder
        shell: bash
        run: echo ${{ matrix.folder }}

      - name: Setup build environment
        uses: './.github/actions/build_setup'
        with:
          branch: "dev"
          dev-aws-profile-name: ${{ env.DEV_AWS_PROFILE }}
          dev-aws-role-to-assume: ${{ env.DEV_AWS_ROLE_TO_ASSUME }}
          dev-aws-region: ${{ env.DEV_AWS_REGION }}

      - name: Make lambda
        shell: bash
        run: |
          AWS_PROFILE_BRAIN_DEV=${{ env.DEV_AWS_PROFILE }} LAMBDA_NAME=${{ matrix.folder }} make specific
    
      - name: Update the .VERSION file
        shell: bash
        run: |
          AWS_PROFILE_BRAIN_DEV=${{ env.DEV_AWS_PROFILE }} LAMBDA_NAME=${{ matrix.folder }} make update_version

  Push_to_PROD_stack:
    if: ${{ github.ref_name == 'prod' }}
    needs: changed_files_dev
    strategy:
      matrix:
        folder: ${{ fromJSON( needs.changed_files_dev.outputs.folders ) }}
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    runs-on: ubuntu-latest    
    timeout-minutes: 10
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
    
      - name: Current lambda folder
        shell: bash
        run: echo ${{ matrix.folder }}

      - name: Setup build environment
        uses: './.github/actions/build_setup'
        with:
          branch: "prod"
          dev-aws-profile-name: ${{ env.DEV_AWS_PROFILE }}
          dev-aws-role-to-assume: ${{ env.DEV_AWS_ROLE_TO_ASSUME }}
          dev-aws-region: ${{ env.DEV_AWS_REGION }}
          prod-aws-profile-name: ${{ env.PROD_AWS_PROFILE }}
          prod-aws-role-to-assume: ${{ env.PROD_AWS_ROLE_TO_ASSUME }}
          prod-aws-region: ${{ env.PROD_AWS_REGION }}

      - name: Publish lambda from DEV to PROD stack
        shell: bash
        run: |
          AWS_PROFILE_BRAIN_DEV=${{ env.DEV_AWS_PROFILE }} AWS_PROFILE_BRAIN_PROD=${{ env.PROD_AWS_PROFILE }} LAMBDA_NAME=${{ matrix.folder }} make push_specific_to_prod